export const SET_USER = "SET_USER"
export const USERS_ERROR = "USERS_ERROR"
export const CREATE_USER = "CREATE_USER"
export const LOGOUT_USER = "LOGOUT_USER"

export const SET_FACULTY = "SET_FACULTY"
export const FACULTY_ERROR = "FACULTY_ERROR"
export const CREATE_FACULTY = "CREATE_FACULTY"
export const LOGOUT_FACULTY = "LOGOUT_FACULTY"

export const CREATE_CLASS = "CREATE_CLASS"
export const CLASS_ERRORS = "CLASS_ERRORS"